# Generated by Django 5.2.7 on 2026-02-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_batch_uploadedfile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
    ]
