# Generated by Django 5.2.7 on 2026-02-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_uploadedfile_is_annotated'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
