# Generated by Django 6.0 on 2026-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlabel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
