# Generated by Django 6.0 on 2026-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_classlabel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='utm_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='utm_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
